---
- name: Install basic items needed to troubleshoot
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - vim
    - net-tools
    - curl
    #- nginx

- name: Set up a backend server to respond to NGINX requests.
  template:
    src: busybox.j2
    dest: "/usr/local/bin/busybox.sh"
    mode: 0750

- name: Set up backend server
  shell: /usr/local/bin/busybox.sh

- name: Custom 404 Page
  template:
    src: 404.j2
    dest: "/var/www/html/404.html"
    mode: 0750