---
- hosts: all
  remote_user: vagrant
  become: yes
  vars:
    - nginx_reverse_proxy_proxies:
      - config_name: app1proxy
        backend_name: backend1
        backends:
          - localhost:3400
        domains:
          - www.example.com
  roles:
    - ansible-nginx-reverse-proxy

