---
- hosts: all
  remote_user: vagrant
  become: yes
  vars:
    - back_end_port: 3200
    - nginx_reverse_proxy_proxies:
      - config_name: app1proxy
        backend_name: backend1
        backends:
          - localhost:3400
        domains:
          - www.example.com
  roles:
    - { role: server-common }
    - { role: ansible-role-nginx }
    - { role: ansible-nginx-reverse-proxy }

